const items = [
	{
		title: 'Twitter',
		href: 'https://twitter.com/JTComlink',
		icon: 'fa-brands fa-twitter',
		// background: '#1d9bf0',
		background: '#0d7ac4',
	},
	{
		title: 'Twitter - Rik',
		href: 'https://twitter.com/cadbanesbounty',
		icon: 'fa-brands fa-twitter',
		// background: '#1d9bf0',
		background: '#0d7ac4',
	},
	{
		title: 'Spotify',
		href: 'https://open.spotify.com/show/7Cxgn8198cn9rysCF8MWzo',
		icon: 'fa-brands fa-spotify',
		subtitle: '',
		// background: '#1db954',
		background: '#16883e',
	},
	{
		title: 'Apple Podcasts',
		href: 'https://podcasts.apple.com/us/podcast/jammed-transmissions-a-star-wars-podcast/id1445333816?itsct=podcast_box&itscg=30200&ls=1',
		icon: 'fa-solid fa-podcast',
		subtitle: '',
		background: 'var(--applePodcasts)',
	},
	// {
	// 	title: 'Instagram',
	// 	href: 'https://www.instagram.com/Jammedtransmissions',
	// 	icon: 'fa-brands fa-instagram',
	// 	subtitle: '',
	// 	// background: '#E1306C',
	// 	background: '#e02766',
	// },
	{
		title: 'Emails',
		href: 'mailto:comlink@jammedtransmissions.com',
		icon: 'fa-solid fa-mailbox-flag-up',
		subtitle: '',
		background: '#52565e',
	},
	{
		title: 'TeePublic',
		href: 'https://www.teepublic.com/user/jammed-transmissions',
		icon: 'fak fa-teepublic',
		subtitle: '',
		background: '#374ECD',
	},
	{
		title: 'Overcast',
		href: 'https://overcast.fm/p4094075-GKfo0m',
		icon: 'fak fa-overcast fa-lg',
		subtitle: '',
		// background: '#fc7e0f',
		background: '#be5a01',
	},
	{
		title: 'Google Play',
		href: 'https://podcasts.google.com/feed/aHR0cHM6Ly9mZWVkLnBvZGJlYW4uY29tL2phbW1lZHRyYW5zbWlzc2lvbnMvZmVlZC54bWw',
		icon: 'fa-brands fa-google-play',
		subtitle: '',
		// background: '#4285f4',
		background: '#206ff2',
	},
	// {
	// 	title: 'Stitcher',
	// 	href: 'https://www.stitcher.com/show/1050712',
	// 	icon: 'fa-solid fa-waveform',
	// 	subtitle: '',
	// 	// background: '#ec8900',
	// 	background: '#ae6500',
	// },
	{
		title: 'RSS',
		href: 'https://anchor.fm/s/d8972e20/podcast/rss',
		icon: 'fa-solid fa-rss',
		subtitle: '',
		// background: '#ee802f',
		// background: '#f26522',
		background: '#ce4a0c',
	},
	{
		title: 'Goodpods',
		href: 'https://goodpods.com/podcasts/jammed-transmissions-a-star-wars-podcast-222540',
		icon: 'fak fa-goodpods',
		subtitle: '',
		background: '#fcdb00',
		color: 'var(--bg)',
	},
	{
		title: 'Amazon Music',
		href: 'https://music.amazon.com/podcasts/79e0b4ef-8009-42a6-9109-c40827194123jammed-transmissions-a-star-wars-podcast',
		icon: 'fa-brands fa-amazon',
		subtitle: '',
		background: '#0077c1',
	},
	// {
	// 	title: 'Hive Social',
	// 	href: 'https://www.hivesocial.app/',
	// 	icon: 'fak fa-hive-social',
	// 	subtitle: '@jtcomlink',
	// 	// background: '#d34eff',
	// 	background: '#be00fd',
	// },
	{
		title: 'iHeart',
		href: 'https://www.iheart.com/podcast/338-jammed-transmissions-a-sta-102467606/',
		icon: 'fak fa-iheart',
		subtitle: '',
		background: '#C6002B',
	},
	{
		title: 'Pocket Casts',
		href: 'https://pca.st/j125cwks',
		icon: 'fak fa-pocket-casts',
		subtitle: '',
		// background: '#F43E37',
		background: '#ea150d',
	},
	{
		title: 'Radio Public',
		href: 'https://radiopublic.com/jammed-transmissions-a-star-wars-Wwogwa',
		icon: 'fak fa-radio-public',
		subtitle: '',
		background: '#CE262F',
	},
	{
		title: 'Castbox',
		href: 'https://castbox.fm/podcasts/Jammed%20Transmissions:%20A%20Star%20Wars%20Podcast',
		icon: 'fak fa-castbox',
		subtitle: '',
		// background: '#f25c31',
		background: '#db3c0e',
	},
]

export default items
